version: '3.8'

services:
  fluent-blazor-app:
    image: fluent-blazor-app
    container_name: fluent-blazor-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8081:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fluent-blazor-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
